env = Environment()

env['APP_TARGET'] = 'LeapApp'
env['APP_SOURCES'] = ['LeapApp.cpp']

env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')
